### PR TITLE
Do not load file in memory for computing sha sum

### PR DESCRIPTION
**Pull request by yohanboniface**
Otherwise download fail on big files or small RAM servers, or both ;)

Thanks for reviewing :)

### CODE REVIEW

**Comment by berdario** [comment]
Uhm, thank you...

I got used to only 64 bit machines, where this problem is moot, but I guess that on 32bit machines you'd be limited to 2-4GB files (you're obviously not strictly limited by the amount of RAM on your server, only by the amount of virtual memory since)

Still, I'd pick your code only as a fallback... I'd need to look up how to detect at runtime the maximum continuous addressable chunk of memory (on both Linux and Windows)

Unfortunately I just started a new job, and this evening I'll depart for a 4day trip without my laptop (hasn't happened in more than 5 years, I think!), so I'll be able to look properly at this only next week

Thank you again

**Comment by yohanboniface** [comment]
> I guess that on 32bit machines

You guessed well :)

Any chance to have a more detailed review soon so we can work that out? :)

Thanks in advance for your time!

**Comment by bochecha** [comment]
@berdario Hi, any news on this? :smiley:

**Comment by yohanboniface** [comment]
Thanks :)

**Comment by berdario** [comment]
I looked into this, and the only way to see if we'll have enough address space is by checking the size of `off_t`

On linux, gcc `off_t` is aliased to `long int`... I guess that I could thus do `ctypes.sizeof(ctypes.c_long)`, but this doesn't guarantee it'll be correct on other platforms. The only true solution would be the CFFI route (which means a dependency on the compiler)

The simplest solution is thus switching back to `.read()` just like in your PR  :)

Sorry for not merging this earlier

**Comment by yohanboniface** [comment]
> Sorry for not merging this earlier

Some "4day trips" are longer than others :D

Thank you again :)

**Pull request merged**
